### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by caralasa136** [UG-Mobile2016/Pr-ctica-2#1]
Tenía entendido que la segunda práctica no se realizaría, por qué mejor no tomamos la práctica 2 como actividad de clase para que quede entendido la realización de la misma ya que sólo se hizo un ejemplo de API y personalmente no me queda claro como programarla.

**Comment by Oswaldofm17** [comment]
Pienso lo mismo profe, la verdad en lo personal se que no podré realizar la práctica porque no logro entender las cosas de manera clara.

**Comment by EmilioSalgado** [comment]
Creo que sería buena idea verlo en clase en lugar de hacerlo como práctica porque no me quedo muy claro el ejemplo que hicimos en clase con la api de github

**Comment by OscarGovea** [comment]
Profe opino lo mismo, creo que con el ejemplo de Retrofit no me quedo tan claro. Ojala que podamos hacer uno más antes de la practica o bien, tomar esta practica como actividad de clase. Saludos

**Comment by JuanCrg90** [comment]
Haremos otro ejemplo el lunes para cerrar el curso, pero **SI HABRA PRÁCTICA** es necesario que practiquen lo aprendido en clase no solo copiar lo que el maestro les pone en el pizarrón, ademas hay bastante documentación en la internet y es tiempo suficiente para realizarla.
